The Big Picture on School Costs||(formerly entitled: <i>For Further Discussion On School Size</i>)<br>

<P>The discussion about school size, both with school boards and in the general public, will not be complete without considering the ancillary costs of big schools.  These are harder to quantify than the capital and staffing costs of additional smaller schools.  If these costs and liabilities are not considered, a shallow look could conclude that schools should be built bigger yet. </P>

<h4>Direct costs to Districts</h4>
 <ul>
  <li>Smaller schools that are closer to the neighborhood have less ongoing transportation costs.  These costs can be significant in big schools that collect students from all over a metropolitan area and they continue year after year. Buses also begin to rule the schedule when significant numbers of students are being bused throughout the city rather than just collecting rural students.</li>
  <li>Schools with large populations in portable units have much higher heating and cooling costs.</li>
  <li>Smaller schools have not needed policemen, surveillance systems, etc. and appear to be much safer.</li>
  <li>While smaller schools will each need a principal, secretary, etc., bigger schools need more assistant principals and other staff.  Those staffing needs should be considered as well in comparisons.</li>
 </ul>
<h4>Costs to the community for which the School District is not liable</h4>
 <ul>
  <li>Since most patrons choose to drive to school, large schools have significantly larger traffic impacts near these schools. Large schools concentrate traffic.  Smaller schools throughout the community tend to have more students walking and spread out the traffic. </li>
  <li>Smaller schools throughout the community create open space and recreation areas for citizens so that the city does not need to tax for those separately.  They provide meeting places for local needs.  They create community amidst sprawl. </li>
  <li>Large schools have more truancy, drug abuse, and gang problems.  These societal problems then impact the community.  </li>
  <li>There is also a greater need for the city to provide more recreation programs since only the top students of large schools are able to participate in school programs.</li>
 </ul>|David N. Cox||AppendixadditionNov2000|1~
Small Schools Offer Real Hope For Communities Of Color|bankstreet.pdf|<i>America's urban high schools are struggling</i><br>

<b></b><br>

<i>Dr. Kappner has been president of Bank Street College in 
New York City since 1995, and was the assistant secretary for 
Vocational and Adult Education for the U.S. Department of Education 
from 1993 to 1995.</i><br>


<p>Not long ago, I traveled to Seattle to join a group of multicultural 
scholars and practitioners and the nation's leading small schools (K-
12) scholars. We were meeting to discuss the potential benefits of 
small schools reform for minority communities. On at least one point we 
were unanimous: for urban centers and communities of color, most high 
schools are failing.</p>


<p>The news out of our high schools is bleak: 
- High dropout rates continue to plague communities of color. 
-African-American and Latino students are retained (required to repeat 
a grade) at alarming rates. 
-Students of color continue to trail their peers on achievement 
indicators.</p>


<p>Leaders, both within and outside minority communities, have been 
searching desperately for answers.  But surprisingly - at least from my 
perspective - few have embraced a strategy that offers a tremendous 
amount of promise: small schools reform.</p>


<p>Small schools work. And they appear to work particularly well with 
disadvantaged students.  Last year, Bank Street College of Education's 
study, Small Schools: Great Strides, chronicled the success of small 
schools reform in numerous Chicago public schools. The average school 
size nationwide is 741 students, and it is not uncommon for urban 
children to attend elementary schools with more than 1,000 students and 
high schools with 3,000 students. By contrast, small schools in the 
Bank Street study enrolled between 200 to 400 students. The difference 
between the small schools we examined and their larger counterparts was 
striking.</p>


<p>We found that smaller learning communities diminish school violence, 
raise academic engagement and performance, and increase attendance and 
graduation rates - the very issues with which minority communities 
across the nation are grappling.  Our research affirms the mounting 
mass of evidence of those who have studied small schools over the past 
decade.  Most promising, small schools reform works within a public 
school framework - an important fact for leaders of color given that 
approximately 95% of African American and 91% of Latino students 
currently attend public schools.</p>


<p>Why are there not more leaders from communities of color championing 
small schools efforts? Why do we allow communities to continue to build 
the sort of gigantic schools that breed alienation and low 
expectations?  I believe that information about the value of small 
schools has simply not reached a broad enough audience.  A just-
released survey from Public Agenda confirms that the majority of 
America's parents and teachers do not place school size high on their 
lists of educational concerns.  Small school reformers are now 
recognizing the need to reach out to leaders in communities of color 
and welcome them into small schools efforts.</p>
 

<p>I recognize the honest concerns some have about small schools. Many 
fear small schools may be prohibitively expensive. Some others - many 
from African American or other underserved communities - worry that 
overly sympathetic teachers in highly personalized learning 
environments, in recognizing the disadvantages faced by their students, 
may not hold students to sufficiently high standards of achievement.</p>


<p>The evidence gives us confidence that these concerns can be surmounted 
by a thoughtful, coherent and diligent approach to the creation of 
small schools. We have seen that small schools can be affordable for 
even the poorest communities.  (Research by Fruchter, Stiefel et al. 
shows that the cost per graduate is actually lower in small schools 
than in large.) We have found that most small schools hold high 
expectations for their students. Small school populations, like large 
school populations, generally reflect the ethnic makeup of the 
communities they serve; where integration is the goal, small schools 
are often more likely to be able to achieve diverse populations. In 
systems that establish clear, progressive guidelines, small schools are 
actually less likely to be segregated than are larger schools.</p>


<p>Interestingly, some minority leaders have recently spoken out in favor 
of charter schools and voucher plans. Their explanation has been not so 
much an embrace of these strategies as a rejection of the status quo. 
The frustration they feel with the ongoing failure of our urban public 
schools to adequately serve students of color is certainly 
understandable. But what is needed now is not an abandonment of public 
schools but rather a commitment to establishing more effective - and 
smaller - learning communities.</p>


<p>Leaders of color should endorse the small schools movement - within 
public school systems - because small schools offer the potential for 
quality education, provide educational opportunities, and foster 
academic and social success.  Small schools may well provide an answer 
to much of what ails today's most difficult-to-reform educational 
systems. Consequently, now is the time for leaders of color to propel 
this movement forward.</p>|by Dr. Augusta Souza Kappner||bankstreet|1~
The Trouble with BIG|bigTrouble.pdf|<h2 class="header">Big Trouble:  Solving Education Problems Means Rethinking Super-Sized Schools and Districts</h2>

	<p>We Utahns love to have everything from our fast-food meals to our trucks “super-sized”; you might even say our families are “super-sized”!  In many cases bigger is better, but not always.  When it comes to schools and school districts, we as a nation have typically consolidated districts to make them larger under the assumption that bigger was better, specifically, more cost-effective with better academics.  Yet several decades of super-size districts have called that notion into question for quality of services and even cost efficiency.  Some districts might be too big, and might do better to DE-consolidate.</p>
	<p><b>Over half of all students in Utah reside in only four of our forty districts.</b>  Our two largest districts, Jordan and Granite, have over 70,000 students each.  Nationally we have about 14,800 school districts.  Jordan, Granite, Davis, and Alpine are in the top 100 for size.</p>
	<p>Many parents in giant school districts nation-wide are not happy with their schools.  Those who can, demonstrate their displeasure by “voting with their feet” and moving their children into private schools.  Robert W. Jewell found a strong correlation between non-Catholic private school enrollment and large district and school size.  He states,"...the larger the districts and schools, the greater the non-Catholic private school enrollments among the states."   Utah seems at present to be bucking the trend.  We have the smallest percentage of private school enrollment of the states.  Perhaps our larger family size has made that option too expensive.  However, there is a growing segment of the electorate that are demanding vouchers and tuition tax-credits.  If passed, these options would make it possible for many more to “opt-out”.</p>
	<p>Support for school choice is becoming almost a litmus test for the majority Republican Party here in Utah.  Even a former Democratic State Party Chair is involved in the push.  School administrators, who have stated their solid opposition, need to address the why, even if they win temporary battles now.  Is the growing desire for private schools because our schools and districts have become too big?</p>
<h3>Big Roots of Dissent</h3>
	<p>What root problem of public education has disaffected so many parents in the last twenty years that they want to place their children in private or charter schools?</p>
	<p>Are poor test results causing parents’ dissent?  Test results can indicate that a problem exists, but they are not the problem itself.  Some people suggest that declining test scores show that students today are not learning as well as they used to; others argue that the test results are being misinterpreted.   Still others say that the tests themselves are not valid indicators of education progress.  In any case, the test results themselves are not driving the school choice movement.</p>
	<p>Is it curriculum?  Utah has not yet had the math wars and reading wars that California and other states have had.  That likelihood is becoming very real now that whole math and the latest version of whole language “balanced literacy” have been adopted by the state office.  The constructivist philosophy of avoiding the discipline parts of learning (which include direct instruction of the basic skills of grammar, times tables, and phonics, etc.) is creating a division among parents and between teachers.  <b>Many parents and teachers want these taught directly but find it increasingly impossible to influence district and state curriculum committees.</b>  Intimidating statements like, “You don’t want to be one of those ‘drill and kill’ teachers do you?” or “Don’t let those old (experienced) teachers influence you as you begin teaching.” or “ You’re the only one who has voiced this concern.” are used to silence or isolate curriculum debate.  This truly is alienating many would be friends of education.</p>
	<p>Consider the debates over the teaching of evolution versus biblical creation of the early twentieth century, sex education, and many others.  There have always been disagreements about curriculum, but people did not consider leaving public education over it.  Regardless of what is done in the next twenty years, curriculum will still be an issue, as well it should be.  Every generation needs to learn, focus, and decide what is of importance and how and to what degree it should be taught.  Beliefs about curriculum, though very germane to the problem, have not caused the call to get rid of public education.</p>
	<p>Are taxes driving the dissatisfaction with public schools?  <b>While Americans have protested taxes since before our nation was formed, in most every state and national poll for the last twenty years Americans have expressed support for increasing taxes IF it would improve schools.</b>  This sentiment opens the debates about where and how these funds should be spent, and whether more money improves schools at all.  But the fact remains that many <b>parents and citizens would be happy to pay much more for education if they had some control of it.</b></p>
	<p>Control is the key.  Who controls the quality, financing, and curriculum of our schools?  While many citizens intuitively feel these decisions are best made by the parents and teachers of students in the local neighborhood, under our current system, for various reasons, the power to make those decisions rests in the hands of school boards and administrators who oversee increasingly large districts.</p>
<h3>Big, how did we get there?</h3>

	<p>In 1900 there were more than 150,000 school districts in the United States.   Single-school school districts were common.  There were even some districts that were so small they employed only one teacher!  As the assembly-line factory-model took hold in industry, the economies of scale began to be understood and applied in other settings such as schools.  Utah had 380 districts until 1915 when they were consolidated into 39 and later the 40 districts we now have. After World War II there was a stronger push nationwide to consolidate school districts in rural areas.  Many people were leaving agriculture for the city, resulting in less students and taxpayers for schools in rural areas.  There were still about 128,000 districts in 1930, but by the end of the 60’s that number had shrunk to 36,000.  Today there are less than 15,000 school districts nationwide.  During this time our cities were growing and with them their school districts.  The net effect was fewer, bigger districts.  We now have 24 districts with more than 100,000 students.</p>
	<p>Parents in the middle of the century were convinced by administrators to allow consolidation of schools and districts for the economies of scale and for increased opportunities.  Many moved to the city for the same reasons; school taxes would be less and schools would offer more because of a bigger base.  At that time the diseconomies of scale (being too big) weren't even on the horizon because our cities and districts weren’t as big as they are today.  In 1959, J. B. Conant, in his report “The American High School Today,” called for an increase in high school size to 400 students.  Educational Research Service, 1971, referring to 26 studies completed between 1939 and 1969, stated that the most common recommendation for district size was 10,000, and that, “The decrease in the total number of school districts has been 85.9%....The job is, however, far from completed.” indicating the need to further consolidate.7  Since then we have increased both school and district size way beyond what the proponents of larger size were suggesting at that time.  We now have high schools of 5,000 and districts up to 1 million students.</p>
<h3>Big disappointments</h3>

	<p>These large districts have not brought the envisioned savings financially.  "Webb & Ohm (1984) found <b>smaller districts more efficient than larger ones in both dollars per student and numbers of administrators per student....</b>"  Antonucci found that there are “penalties of scale.” Instead of making up a larger percentage of the budget as school districts size increases, the percentage spent on teachers, books, and teaching materials goes down!  He writes, “Paradoxically, <b>the larger a school district gets, the more resources it devotes to secondary or even non-essential activities.</b>”  McGuire, in a 1989 study found, “As specialization in staff grows, program offerings expand, and administrative personnel increase, problems of coordination and control also increase.  And in large systems, time and energy are more likely to be shifted away from core service activities.”  Antonucci also writes, “And let’s not forget the labor implications.  Which district is more likely to have difficult contract negotiations or work stoppages?  The district with 15 bus drivers, or the one with 677 bus drivers?”</p>
	<p><b>1999 Utah administrative costs per pupil show little difference between large districts and small unless one gets below 1000 students.</b>  Below 1000 students the administrative costs go up. (<a href="../AdminCostsTable.html" title="See Figure 1" target="_blank">See Figure 1</a>)  The three lowest districts in administrative cost per student were Logan with 5,840 students - $181 cost per student (cps), South Sanpete with 2,878 students - $198 cps, and Juab with 1796 students - $207 cps.  Alpine with 45,208 is next with $237 cps. In the 2000 legislative audit on class size reduction monies, the smaller districts were better able to account for specific funding than big districts because the big district budgets were so complicated.</p>
	<p>Nor have bigger districts necessarily provided better education.  Cotton, in her review of 100 research projects observes that, “<b>The states with the largest schools and school districts have the worst achievement, affective, and social outcomes.</b>”  According to Webb the researchers have fallen into two camps, those who see no advantage for big districts and those who find "...that achievement drops as enrollment levels rise." She states that this is even more evident in lower socio-economic populations,"...there was a strong, consistent negative correlation between district size and student achievement in low-SES populations."  Walberg goes even farther to show a direct line, negative relationship of the states with large district size and test results.  Jewell states point blank that, "<b>Students in states with smaller districts and smaller schools have higher SAT and ACT scores.</b>”</p>
	<p>Comparisons with Utah school districts 1997-2000 SAT scores are revealing.  (<a href="../5thGrade.html" title="See Figure 1" target="_blank">See Figure 2</a>)  In both 5th and 8th grade test scores, the smallest districts score highest within their expected range (99% and 74% of expected range).  Medium small districts score next highest (65% and 47%), medium size score next (54% & 37%), with the largest districts scoring lowest in their expected range (36% & 32%).   11th grade scores do follow the socio-economic expectations which are upward with district size but this may be because the lower scoring students in bigger districts have dropped out.  <b>Larger schools, which are mostly in the larger districts, have higher dropout rates</b> prompting the analysis that while smaller schools are slightly more expensive, the cost per graduate is less in smaller schools.</p>
<h3>Big Districts = Big Schools</h3>

	<p>Very closely tied to the district size issue is the school size issue.  What seems to be true with districts has even more research showing it to be true with school size.  Cotton and Irmsher in their reviews of over 100 research projects regarding size show conclusively that bigger is not better once schools go beyond a certain size.  Irmsher writes, “Michael Klonsky (1995), and Mary Anne Raywid (1995), and others report that <b>large school size hurts attendance and dampens enthusiasm for involvement in school activities.  Large schools have lower grade averages and standardized-test scores coupled with higher dropout rates and more problems with violence, security, and drug abuse.</b>” She says that with smaller schools, “Security improves and violence decreases, as does student alcohol and drug abuse.” Cotton states, “<b>Behavior problems are so much greater in larger schools that any possible virtue of larger size is canceled out be the difficulties of maintaining an orderly learning environment.</b>”</p>
	<p>Larger schools are not necessarily less expensive either.   “Generally, there is agreement that unit costs are higher in the smallest and largest schools.  Various studies characterize per-pupil school costs as having a U-shaped average cost curve, where costs are high in both the smallest and largest schools.” When cost per graduate is calculated, smaller schools are a better deal.</p>
	<p>It appears that <b>district size is probably the most direct cause of school size.</b>  Jewell says that large schools are concentrated in large districts.  He shows that Utah is 6th in average district size and also 6th in average size of school. This connection makes sense when one considers how school buildings are funded.  Buildings are funded through voter approved bonds.  When a district is large, administrators find it hard to get positive votes for bonding in areas that do not need the new school.  These areas are reluctant to increase their taxes because they don't see the need and won't feel the benefit.  Over time some bonds don't pass, forcing administrators to build fewer schools.  Those that are built must then be made bigger.  To gain voter approval in non-growth areas, administrators then offer additions to existing buildings making them bigger as well.  Therefore <b>in big districts both old and new buildings end up bigger.</b></p>
	<p>There may be other reasons that promote larger schools.  Patrons needing another school may want everything that was built or installed in the last school built.  The booster club may want more enhanced sports facilities, for instance, making it politically necessary to add something to the bond for the older schools to buy voter approval in those areas. This may make the bond bigger than desired and so instead of building two smaller schools that are needed, administrators compromise and build one larger one with all the extras.</p>
	<p>Utah’s big districts have public perceptions that the other side of the district is getting more benefit than their side.  Davis and Alpine’s north and south sides and Granite and Jordan’s east and west sides have fought each other for years over which direction the tax dollars are flowing.  <b>Smaller districts may be more likely to pass bonds because the community as a whole would see the need and feel the benefit.</b>  They would not have to fight another community for political power and tax dollars.  They would not have to take from another area for their own benefit with the resulting negative feelings.  <b>And they might decide that the extras weren’t worth the extra taxes.</b></p>
	<p>In areas of high growth, school size continues to grow, seldom reversing itself.    One reason may be that the growth also means the district grows and with it, the aforementioned problems.  An additional
	  problem presents itself here for future discussion, how does a district build more or smaller schools on land that already has houses on it? If a school is not built with a new development, the land
	  for a new school becomes very expensive and usually can only be acquired by condemnation procedures. This makes it politically very difficult and prohibitively expensive to purchase.</p>
	<p>Some districts have tried to solve big school problems with the “school within a school” approach.  This is an attempt to gain the recognized benefits of smaller size without really becoming smaller and has resulted in some mixed improvement.  The idea is to reorganize into two or more smaller groupings within the existing building.  “The major challenge to schools within schools,” writes Mary Ann Raywid, “has been obtaining sufficient separateness and autonomy to permit staff members to generate a distinctive environment and to carry out their own vision of schooling.” In 1996 Howley reported, “If size is a structural phenomenon, however, caution is warranted in approaching the simulation of small size through such mechanisms as “schools-within-schools” and “house plans” (Meier, 1995; Oxley, 1994; Raywid, 1996).  In general, despite substantial popularity, research on the effectiveness of simulating small size as a way to restructure is very limited (Raywid, 1996).” Transportation is not alleviated with this model either.</p>
	<p>Similarly some big districts have tried to gain the advantages of smaller neighborhood districts using ideas such as subdistricts (Los Angeles School District, 2000), cluster and cone councils that some Utah districts use, or attempting to push more control to local school levels.  It is very difficult to really turn over control and responsibility to these groups, however, because they are not legally the entity in charge.  They cannot raise revenues or allocate them, and this leaves them as mere arms of the larger organization.  "Modern means of decentralizing funding and governance within multi-layered educational organizations - state accountability schemes, school-site management, New York City's community boards, and Chicago's local school councils - have yet to prove their value.  Nor have 'home rooms' and 'schools within schools' shown that they can recapture the advantages of small schools." ‘Kincaid concluded: 'Virtually all of the factors most associated with academically effective education are school- and neighborhood-based.  Yet, we have shifted more control and financing of education to state and national institutions."</p>
<h3>Big Conclusions</h3>

	<p>What does the current state of affairs portent for the future?  According to the 1999 Fall Enrollment Report from USOE, 85% of Utah’s high school students are in schools that research show are too big.  Utah is among the highest in district size.  <b>It may not be possible to build smaller schools without creating smaller districts.</b>  The current situation is not necessarily less expensive either.  <b>Excessive transportation costs and traffic problems resulting from schools that are too big have not been addressed in this report.  Utah’s smaller districts score better, not because the educators of big districts try less, but because the bureaucracy, which a large district must have for control, ties their hands.</b>  It certainly does not engender community spirit toward a common goal in education.  Substantial studies show that bigger is not better and that ‘bigness’ is alienating citizens toward our educational institutions.  This cannot help but influence other governmental entities such as the relationships with cities inside these megadistricts.</p>
	<p>This alienation is depleting local support, and that will result in increased state controls and diversion of funding for basic instruction into accountability schemes in an attempt to force quality, quality that will become increasingly elusive.  Utah’s scores seem to have leveled out or are starting to decline.  Growth of population is continuing and will result in ever bigger schools and further distance of the districts from the citizens.  Back in 1989, Walberg intimated the following as what we could expect as a result of becoming too big.  He listed:</p>
  <ul>
   <li>declarations of educational bankruptcy and state appointment of “receiverships” of new boards and central staff;
   <li>breaking up large-city districts into free-standing smaller units;
   <li>suits by parents for failing to employ state-of-the-art educational practices;
   <li>litigation by graduates for fraudulent services and diplomas;
   <li>magnet schools and choice plans within and outside districts and the public sector;
   <li>and vouchers and tax rebates for private or public tuition.
  </ul>
      <p>He further wrote, “These schemes are motivated by the desperation of some legislators, business people, citizens, and parents who wish to employ the courts or market-like competition to improve the efficiency of schools, particularly those in large districts, that seem unable to respond constructively to their clients and society.”</p>
	<p>Most of these consequences we have begun to see coming true, if not in Utah then elsewhere in the country.  Of the six, only one has any future for really improving the education of the general public and that is breaking up our large districts.  State takeovers would be completed socialism.  How could the state possibly run a district better?  Suits and litigation tie more red tape around a bureaucracy that is already floundering.  Magnet and charter schools are only imitations of what could be found with smaller schools in smaller districts. A charter school is essentially a one-school, new district that has no local tax base.  Vouchers and tuition tax-credits, though very enticing to true believers in individual freedoms and responsibilities, will not gain wide-spread voter approval or improve public schools if implemented. They too, will get wrapped up in litigation.</p>
	<p><b>Setting a limit on the size for both districts and schools and creating an orderly way for setting up these new districts, will achieve better academics and a more efficient use of tax dollars long term.</b>  It will encourage more participation by both students and citizens.  Cities and schools will work together to solve transportation and traffic problems around schools, as well as future development problems.  Why? Because <b>only when our noses are pushed into our own messes do we seem to cleanup after ourselves and solve similar problems for the future.</b></p>
	<p>Smaller districts and schools bring the problems and opportunities back to the local level.  This spurs innovation, flexibility, and commitment by both parents and teachers.  We cannot build students without building parents at the same time, and that builds citizenship as well.  <b>Only by creating new, smaller districts will we return liberty and responsibility to the local parents and teachers.  Only then will true accountability be accomplished.  Only then will true educational quality and efficiency be possible to achieve.</b></p>
<h3>Bibliography:</h3>
<br>
<ol>
 <li>Robert W. Jewell, "School and School District Size Relationships, Costs, Results, Minorities, and Private School Enrollments" Education and Urban Society, 1989 pp. 140-153.
 <li>As one example, BYU’s 1999 Poll of The Public’s Attitudes Toward the Public Schools in Utah, by the Department of Educational Leadership, shows a steady increase from 1994’s 57% support to pay more taxes to help raise the standard of education in Utah, to 59% in 1997, 62% in 1998, and 64% in 1999.  Gallup polls of the 1990’s have also confirmed this nationwide.
 <li>Minutes of Education Interim Committee, Utah Legislature, September 16, 1987.
 <li>Pipho, C., "Rural Education" Phi Delta Kappan,  1987 pp. 6-7.  See also: McGuire, Kent, “School Size, The Continuing Controversy” Education and Urban Society, 1989 p. 173.
 <li>Antonucci, Mike, “Mission Creep: How Large School Districts Lose Sight of the Objective -- Student Learning” Alexis de Tocqueville Institution Brief #176, November 17, 1999.
 <li>Conant, J. B., "The American High School Today" Carnegie Series in American Education, 1959.
 <li>Webb, Florence R., "A District of a Certain Size" Education and Urban Society, 1989 p. 127-128
 <li>ibid, p. 130.
 <li>ibid, p. 134-135.
 <li>Walberg, Herbert J., “On Local Control:  Is Bigger Better?” University of Chicago, No. 59 Nov. 22, 1993.
 <li>Cotton, Kathleen, <a href=http://www.smallerschools.org/nwrel.shtml>“School Size, School Climate, and Student Performance”</a> Northwest Regional Educational Laboratory, Close-Up #20.  	(http://www.nwrel.org/scpd/sirs/10/c020.html)
 <li>Irmsher, Karen, <a href=http://www.smallerschools.org/digest113.htm>“School Size”</a> ERIC Digest 113 July 1997.  (http://www.library.uluc.edu/schoolreform/sconsol.htm)
 <li>Walberg, Herbert J., “District Size and Student Learning,” Education and Urban Society, 1989 p. 128.
 <li>K. McGuire, “School Size: The continuing controversy,” Education and Urban Society 21 (2, February): 164-174
 <li>Langdon, Philip, “Students do better in Small Schools so why have we been making schools bigger?,” The American Enterprise, January 2000 p. 25.
 <li>Costs were compiled by taking the total reported administrative costs in each district for 1999 and dividing by the number of students in each district.
 <li>Raywid, M. A. “Family choice arrangements in public schools: A review of the literature.” Review of Educational Research, 55(4), p. 455, (1985).
 <li>Howley, Craig, “Ongoing Dilemmas of School Size: A Short Story” ERIC Digest, December 1996.
</ol>|David N. Cox||bigTrouble|2~
Recommendation to the County Commission|countyRecommend.pdf| June 18, 2004
 <p>My vote and recommendation to the County Commission is that the Pioneer School District Proposal be placed on the ballot for the approval of the voters.  The people as a whole have a right to make this decision.  Small groups with vested interests or ulterior motives should not decide the issue.</p>

<h3>More Efficient in the Long Term</h3>
 <p>The Alpine district is not the largest district in the state or nation, though it is 4th largest in the state and among the largest 100 out of 14,000 districts nationwide.  Alpine is not a “problem” district as compared to many big city districts.  However it is growing fast with over 50,000 students. Many studies have shown that economies of scale are U-shaped.  Too small and too large are more expensive.</p>
 <p><b>Nationally, larger districts put a smaller percentage of their revenue directly to the classroom.</b>  They have a larger bureaucracy.  Some have said they become more of a social agency than an educational agency.  In big districts people think the district is the “deep pocket” and can afford another program or funding can be taken from another “richer” side of the district.  Consequently, the only way to contain the ever-increasing growth in programs and costs for education is to bring it back to the local community level, where citizens are less likely to pick their neighbor’s pocket for another program.  Some have said that “school community councils” bring local control.  However this is not the case.  They have neither real power nor responsibility.  They don’t control budgets, taxes, curriculum, or personnel.  They are merely a nice way to get buy-in from the patrons.</p>
 <p><b>The financial study done by BYU students gave the false idea that voting for this division increases taxes.  Dividing the district does NOT raise taxes.</b>  Taxes would not be raised unless people elected board members that were willing to raise them or by a vote of the people. Even if the study were accurate, it does not change my opinion, because of the value of local control and involvement and what the studies show of the product of smaller districts.  However, I do have problems with the value of the study because it did not research what the revenues really would be, so no choices can be made from the study.  It did not conclusively establish what the tax base would really be.  Nationally, big districts are more expensive.  In Utah there is little difference in administrative cost per student between large and smaller districts unless they are smaller than 1000 students.  <b>If charter schools can do it effectively with NO tax base why could we not do it WITH our tax base?</b></p>
<h3>Smaller Schools Needed than what Alpine is Providing</h3>
 <p>Research says that while all groupings are benefited, numerous studies particularly point to the fact that lower-income areas are the most benefited by having smaller districts.  My own studies of Utah test scores included on my website show this to be the case.</p>
 <p><b>There is even more research supporting the absolute need to build smaller schools to bring accountability, safety, less violence and crime, academic improvement, parental involvement, connectedness, and even teacher retention.</b>  This is combined with the fact that the most accurate predictor of school size is district size (i.e. the larger the district, the larger the schools).  This is proving more and more to be true in Alpine School District.  To get enough votes to pass a bond requires the district to build something for everyone.  This means larger schools even in the non-growth areas.  In similar growth areas in the country, this has eventually led to schools of three to five thousand students.  We already have elementary schools of over 1400.</p>
 <p>School district average size nationally is about 2500 students.  <b>Pioneer S.D. would be over 8000 students and would be bigger than two-thirds of the districts in Utah.</b>  It would be just smaller than Tooele School District.  It would have the challenges of growth, as does Tooele S.D.  This can be handled by the use of K-8 or 7-12 grade buildings.  These models are being implemented nationwide because they are more economical, closer to the neighborhoods (less transportation costs), have better behavior, test scores, and students even do better in college afterward.</p>
<h3>Now is the Time</h3>
 <p>Some have said that we need to divide, but that now is not the time.  They say wait until we have more tax base or some other reason.  Now IS the time.  <b>The window of opportunity is open.</b>  If this proposal fails, I believe <b>we will not get another chance.</b>  No one will sacrifice all that time and their reputation again.  Much as I hate to mention it, once passed it can be reversed.  Districts can be consolidated.  However, once citizens get a taste of freedom I doubt they will want to give that up.</p>
 <p>There is desire nationwide to divide large districts.  People have been trying to split Los Angeles and Las Vegas and many other places for years and have not been able to because they are already way too big.  <b>The bigger the district gets, the bigger becomes the political networks and unions determined to fight the split.</b>  While several district divisions have taken place in the last 20 years, they have all been smaller districts that don’t have that big network in place to kill the movement.  Hence, <b>the bigger a district is, the harder it is to split it, even though the need is greater.</b></p>
 <p><b>There will always be reasons thought up to oppose it by those fearful their jobs would not be needed.</b>  Thus, if we understand the governance issue and agree that it is right and needed at some point in time, we need to take the chance when it is given or it won’t be offered again.  If we wait until some later date to attempt this, the exact same arguments will be made against it from some other side of the district.  They will be afraid it will hurt them.  The longer we wait, the harder it will be to divide, even though more obviously needed.</p>
<h3>Charter Schools are Already Dividing the District</h3>
 <p><b>The district is already starting to be split by means of charter schools.</b>  If trust is not regained toward public education by giving the governance back to the people in local communities (the real owners of the schools), these basically single-school school districts will continue to multiply, as will private schools.  If the district is not divided into organized community-by-community districts, <b>it will be done anyway, in a fragmented way;</b> piece by piece, in a more disjointed fashion that will not serve the citizens as well and <b>will ultimately cost more than dividing the district.</b></p>
 <p>Our bodies would not function better as one big cell.  <b>To grow, we must divide.</b>  If our founding fathers had worried about whether it was financially viable to break with Britain, or if they had thought that the timing was not right, we would not be a country today.  It could not have happened later.  This district division is based on correct principles.  It is the right thing for our area.  It is the right thing for Utah.  <b>It is right for America, and someone has to be the first.</b></p>
|David N. Cox|countyRecommend||2~
Input on Creation of Pioneer School District|districtCreation.pdf|<p>The decision to pursue division of the Alpine School District is one that has had a lot of thought and study given to it. Alpine School District is not the largest district in the state or nation, though it is 4th largest in the state and among the largest 100 out of 14,000 districts nationwide. Alpine is not a “problem” district as compared to many big city districts. However it is growing fast with over 50,000 students. So what compels so many people to want to create their own, community district? Perhaps I cannot speak for all of them, but here are my reasons:</p> 
<ol>
 <li>Research, of which I have collected some on my website at <a href="http://www.smallerschools.org">SmallerSchools.org</a>, supports the notion that <b>a smaller structure will give a better product, at a better price long term, while building the citizens </b>at the same time. While all groupings are benefited, numerous studies particularly point to the fact that lower-income areas are the most benefited by having smaller districts and schools. My own studies of Utah included on my website show this to be the case. 
 <li>Nationally <b>larger districts</b> put a smaller percentage of their revenue directly to the classroom. They have a larger bureaucracy. Some have said they <b>become more of a social agency than an educational agency.</b> For those willing to read it, there is much research supporting the idea that the best thing we could do for public education is to divide the large districts, reintroducing them to the communities they serve. <b>The only way to contain the ever-increasing growth in programs and costs for education is to bring it back to the local community level</b> and schools’ “community councils” don’t do that. They have neither real power nor responsibility. They don’t control budgets, taxes, curriculum, or personnel. They are merely a nice way to get buy-in from the patrons. 
 <li>There is even more research supporting the absolute need to build <b>smaller schools to bring accountability, safety, academic improvement, parental involvement, connectedness, and even teacher retention.</b> This is combined with the fact that the most accurate predictor of school size is district size <b>(i.e. the larger the district, the larger the schools).</b> This is proving more and more to be true in Alpine School District. I do not believe we will be able to pass the next bond for buildings if we stay together. This will mean even larger schools. In similar growth areas in the country, this has eventually led to schools of three to five thousand students. We already have elementary schools of over 1400. </p>
</ol>
<p>These are perhaps my biggest reasons for desiring a new district. It will bring more accountability from the educators and the taxpayers toward each other than all the state-imposed accountability or tax-cap schemes devised. Does this guarantee things will be better? No, it only makes it more likely. Freedom is always somewhat of a risk, but it provides much more opportunity. When the United States split off from Britain, it did not appear economically to be a wise choice, at least in the short term, but it sure has been long term. There are also answers I have to the criticisms of others regarding finances and whether now is the time. </p>
<ol>
 <li>The financial study does not change my opinion even if it is accurate, because of the value of local control and involvement and what the studies show of the product of smaller districts. However, I have problems with the value of the study because <b>it did not research what the revenues really would be</b>, so no choices can be made from the study. The reports of the study gave the false idea that voting for this division increases taxes. <b>Dividing the district does NOT raise taxes.</b> Taxes would not be raised unless people elected board members that were willing to raise them or by a vote of the people.  Nationally big districts are more expensive. In Utah there is little difference in administrative cost per student between large and smaller districts unless they have less than 1000 students. <b>If charter schools can do it effectively with NO tax base why could we not do it WITH our tax base?</b>
 <li>Some have said that we need to divide, but that now is not the time. They say wait until we have more tax base or some other reason. Now IS the time. <b>The window of opportunity is open. If this fails, I believe we will not get another chance.</b> No one will sacrifice all that time and their reputation again. Much as I hate to mention it, once passed it can be reversed. Districts can be consolidated. However, once citizens get a taste of freedom they will not want to give that up I believe. There is desire nationwide to divide large districts. People have been trying to split Los Angeles and Las Vegas and many other places for years and have not been able to because they are already way too big. The bigger the district gets, the bigger becomes the political network and union to fight the split. While some district divisions have taken place in the last 30 years, they have all been smaller districts that don’t have that big network in place to kill the movement. Hence, <b>the bigger a district is, the harder it is to split it even though the need is greater.</b> There will always be reasons thought up to oppose it by those fearful their jobs would not be needed. Thus, if we understand the governance issue and agree that it is right and needed at some point in time, <b>we need to take the chance when it is given or it won’t be offered again.</b> 
 <li><b>The district is already starting to be split by means of charter schools.</b> If trust is not regained toward public education by giving the governance back to the people in local communities (<b>the real owners of the schools</b>), these single-school school districts will continue to multiply. If the district is not divided into organized community-by-community districts, it will be done anyway, in a fragmented way; piece by piece, in a more disjointed fashion that will not serve the citizens as well and <b>will ultimately cost more than dividing the district.</b> 
</ol>
<p>The tax-base is not the problem in this issue. There is enough if we make good choices. Three-fourths of the funding is not provided that way. The real issue is “Are we willing to let go and sail our own boat?” The research supports it (<b>if we’ll read it</b>)! </p>
|David N. Cox||districtCreation|2~
Smaller Districts|DistrictSize.pdf|<P>"<b>School district size has a consistent negative relation to student performance and is highly significant in three out of four tests</b>." -W. Niskanen &amp; M. Levy, University of California, Berkeley<SUP>4</SUP></P>
<P>The main reason taxpayers have not passed more bond elections for more and smaller schools is that our districts are too large.  Their suspicions say that their money is going to benefit some other part of the district.  The district is no longer their community, but it is rather a larger government entity.  </P>
<P>Setting up a way and a criteria for when to split districts, will provide a more sure way of correctly solving problems in the future which will help prevent the malaise affecting us now.</P>
<P>At present we have a situation where problems are allowed to fester and people to be alienated despite the herculean efforts of current district administrators.  Relatively few people are involved.  Instead of having a local board member to talk with when problems happen, <b>we have board members that represent areas which are often larger than that of state legislators</b>.  When problems come up, they get hundreds of calls, overburdening them and making impractical both the serving and educating of the people.  As such, the people, who generally don't know their board member, go to their legislator over the problem.  Legislators have so many other state issues to worry about, that few really understand the details or the big picture of education, like a board member would.  After a while, legislators begin to try to solve the problems and generally either encumber the system or make enemies of educators with mandates that don't work.  The next step is, after being alienated, to attack or refuse to advocate for education.</P>
<P>Public education was set up to function more like a local corporation, with a board of directors and a CEO.  <b>American education was never set up to be a department of state government</b>.  It was set up to be a local, publicly owned, non-profit corporation.  This worked well when communities and districts were relatively small because more people were involved per capita and therefore more understood needs, responsibilities, and costs.</P> 
<P>Now, where districts have become big, few people per capita are involved, budgets are big and too complicated for most people.  The larger the district, the more people believe the district has deep pockets.  As such <b>they ask for more and are less willing to pay the needed taxes for the increasing burden</b>.  When a district is small, the people can and have to make the decisions to either pay up or forget the benefit.  They know that their money is going to themselves not to someone else.</P>
<P>Research shows that the same benefits that small <b>schools</b> have are the same ones that small <b>districts</b> have.  There are diseconomies of scale with costs.  "...Webb &amp; Ohm (1984) found smaller districts more efficient than larger ones in both dollars per student and numbers of administrators per student...."<SUP>5</SUP>  Very small districts are expensive and so are large districts.  <b>There seems to be an optimum size for classes, schools, and districts</b>.  <b>We need to find that size for each and work to keep in line with it, for in the long-run it will be less expensive and provide a better product</b>.</P> 
<P>To set up a criteria for splitting districts will require help from district administrators both rural and urban.  My observations show that districts function best at between 2,500 - 5,000 students or roughly one high school and its feeder schools.  I am convinced that divisions would have to be instigated at the state board level because no district would bring it upon themselves.  However, after the split has occurred, the people will find new freedom to tailor their schools to their needs.</P> 
<h4>ADDITIONAL NOTES</h4>
<P><SUP>4 </SUP><u>Education and Urban Society</u>, Feb 1989, "A District of a Certain Size, An Exploration of the Debate on School District Size" <i>by Florence R. Webb, University of California, Berkeley.</i></P>
<b> The following is a compilation of quotes by researchers on the subject of school district size in relation to their mission.  All quotes are from various articles taken from <i>Education and Urban Society</i>, Feb 1989.</b></P>

<P>&nbsp;&nbsp;&nbsp;<b>From "District Size and Student Learning," by Herbert J. Walberg University of Illinois at Chicago.</b></P>
<P> "But it appears that smaller districts on average may be more effective and efficient: Their students appear to score higher on standardized tests (other things being equal) and they may be more satisfying to parents and citizens."   </P>
<P> "...large schools are concentrated in large districts." <i>Coleman and Laroque (1986)</i> </P>
<P> "Similarly, Strang (1987) documented the rising power of state bureaucracy and the decline of local autonomy even as districts grew larger.  He saw the transformation of U.S. education from informal community control into large-scale bureaucratic organization stemming in part from the expansionary role of the states." </P>
<P> "Smaller districts (and privately financed schools) can ill afford such specialization but may actually have advantages in maintaining a cohesive general curriculum; adapting to local preferences and conditions; and strengthening ties among school, home, and community.  Such districts may do fewer things better and avoid spurious categorization of students and needless administrative complexity." </P>
<P> "If larger districts do worse, then the largest might be expected to do worst.  Many citizens and educators, indeed, believe that such cities as Atlanta, Detroit, Los Angeles, and New York are education catastrophes.  Some policy analysts have proposed radical schemes that would have received little serious consideration a decade ago.  These include...<b>breaking up large-city districts into free-standing smaller units</b>;...." (emphasis added.) </P>
<P> "...the consolidation of districts into larger units that has been taking place for the past half century may have been a move in the wrong direction.  Generally, it appears that the smaller the district, the higher the achievement when the socioeconomic status and per-student expenditures are taken into account.  Why? Superintendent and central staff awareness of citizen and parent preferences, the absence of bureaucratic layers and administrative complexity, teacher involvement in decision making, and close home-school relations--these may account for the apparent relative efficiency of small districts in North America." </P>
<P>&nbsp;&nbsp;&nbsp;<b>From "Size, The Ultimate Educational Issue?" by Barney M. Berlin, Robert C. Cienkus, Loyola University of Chicago.</b> </P>
<P> "Why does smaller seem to work better?  In their own ways, all of the authors have answered this question.  The literature on educational change repeats the answer.  That is, people seem to learn, to change, and to grow in situations in which they feel that they have some control, some personal influence, some efficacy.  Those situations in which parents, teachers, and students are bonded together in the pursuit of learning are likely to be the most productive." </P> 
<P>&nbsp;&nbsp;&nbsp;<b>From "School and School District Size Relationships: Costs, Results, Minorities, and Private School Enrollments" by Robert W. Jewell, University of Chicago.</b> </P>
<P> "...a significant number of families may choose to send their children to private schools because they wish to avoid educational associations for their children with large public school districts and/or large public schools." </P>
<P> "Students in states with smaller districts and smaller schools have higher SAT and ACT scores." </P>
<P> "Minority public schools in the United States are concentrated in states that have large school districts and school districts that have large schools."(Could this be one reason why minorities are struggling to improve?) </P>
<P> "Per-pupil expenditure averages ... have no significant statistical relationship ...(to) average school district sizes, proportions of students in large districts, or average school sizes." (Large district size does not appear to be less expensive.) </P>
<P> <b>!!!</b> "...private school enrollment ... has strong positive relationships with district size and school size -- the larger the districts and schools, the higher the proportion of non-Catholic private school enrollments among the states." </P>
<P>&nbsp;&nbsp;&nbsp;<b>From "School Size, The Continuing Controversy" by Kent McGuire, Education Commission of the States.</b> </P>
<P> "Generally, there is agreement that unit costs are higher in the smallest and largest schools.  Various studies characterize per-pupil costs as having a U-shaped average cost curve, where costs are high in both the smallest and largest schools." </P>
<P> "The number of school districts was then reduced from approximately 128,000 in 1930 to 36,000 in 1960.  There are fewer than 16,000 today." </P>
<P>&nbsp;&nbsp;&nbsp;<b>From "A District of a Certain Size, An Exploration of the Debate on School District Size" by Florence R. Webb University of California, Berkeley.</b> </P>
<P> "...Webb &amp; Ohm (1984) found smaller districts more efficient than larger ones in both dollars per student and numbers of administrators per student...." </P>
<P> "Real spending on K-12 education in the U.S. increased more than fourfold -- after inflation (National Center for Educational Statistics, 1973, in Guthrie, 1979) -- during the period when district consolidations were increasing district size one hundred and fifty fold." </P>
<P> "...achievement drops as enrollment levels rise." </P>
<P> "I believe splitting districts to optimum size would solve the accountability problem on a local rather than state level and provide happier citizens and teachers." </P>
|David N. Cox||DistrictSize|2~
Alpine School District Division Hot Topics|divisionHotTopics.pdf|<h2 class="header">Letter to the Editor concerning the Alpine School District Division proposal</h2>

<p>July 10, 2004</p>
<p>Dear Editor,</p>

	<p>Since it now appears unlikely that any debate will be arranged before the July 28th public hearing, I would like to respond to the charges made against the Alpine School District Division proposal.</p>
	<p>The proposed Pioneer District would geographically be equal in size to the rest of the district, and Lehi is now the third largest city behind Orem in Utah County.  The proposed district would be bigger than two-thirds of the districts in the state, with over 8000 students, and growing.</p>
	<p>Much research is available on my website at <a href="http://www.smallerschools.org">www.smallerschools.org</a> that shows the value of community-sized districts and the problems that bigger districts create, including the strong tendency to build bigger, more extravagant schools instead of neighborhood schools, the organization becoming more of a big bureaucracy, and the U-shaped diseconomies of scale (costs go up if the organization gets too big as well as too small).  <b>The opponents seem unwilling to discuss or even read any of this information specifically, so let's discuss their charges.</b></p>
<h3>Cost</h3>
	<p>The big one is cost.  Will the division result in a 40% increase in school taxes over five years (24% of total property tax or $100 on a $100,000 home per year)?  This is about the rate of increase we have been experiencing anyway.  <b>Creating a Pioneer District does NOT automatically raise taxes by itself.  Taxes would only go up if the new board voted to.</b>  The projection, which DID include new buildings, was figured only from averages and based on current expenditures.  <b>No actual revenues were calculated because the District and the State Office of Education said it would be too hard to figure.</b>  The actual, complete tax base was also not computed.</p>
	<p>The vast majority of your property tax for schools is taken by the state, added to by the state income tax, and redistributed so that funding for each student is equalized regardless of the tax base of each area in the state.  There are a few additional small revenue streams that are subject to the tax base in the general fund.  Last year these included the voted leeway - $9.7 (million), board leeway - $3.0M, recreation - $0.8M, transportation extras - $1.3M, tort liability $0.2M, and an additional amount allowed called "10% of basic" - $6.9M, totaling about $22 million.  Out of a general fund budget of about $230 million that is about 10%.  So only 10% of the general fund (which pays for salaries, benefits, and programs) is based on tax base.  In other words we might drop a percent or two in the general fund overall because of tax base.  That doesn't mean a big tax increase or cuts in benefits and salaries.</p>
	<p>Bonding for buildings, on the other hand, IS based on tax base almost completely (some comes from the state).  We would have to change some things on the kinds of schools we would build.  Many districts nationwide are going to K-8 grammar schools or 7-12 high schools and are doing away with jr. highs (usually the worst time of their K-12 experience) as they can.  These schools can be built in walking neighborhoods, saving transportation costs for both schools and parents, and are still more efficient to build than current practice.  They also have better student behavior and scores, parental involvement, and support from the community.</p>
<h3>Jobs</h3>
	<p>The teachers' union is charging that all teachers would stay with the old side of the district, which would then lay off younger teachers for the new district to hire.  This is obstructionist nonsense.  <b>Employees would stay in the buildings they are currently teaching in with all their accrued seniority, etc.</b>  It is regrettable that union threats of litigation are being made because <b>they are only made to prevent the division by intimidation, rather than to protect the teachers</b>.  There are currently less than half of the teachers in the Pioneer area that are members of the union and they are afraid this could become the first non-union district in the state.</p>
	<p>Will the teachers' salary and benefits only be guaranteed for one year?  Yes, that's all they are now in the District.  Each year the District negotiates a contract, which can be changed from year to year.  The new district would have to be free to negotiate (with or without a union) with the teachers for future years.  It wouldn't be fair to bind them to what some other district did, would it?</p>
	<p>Pioneer District will have to compete with Alpine, Provo, Nebo, Jordan, and others for teachers and so <b>salaries are not going to go down</b>.  It is possible that we would change our priorities on some programs.  Some might get more, some less, but <b>WE would decide what our communities thought was most important instead of six other board members from other communities.</b></p>
 <h3>Conclusion</h3>
	<p>The opponents claim that we are not listening to the community, that they are the vast majority.  If so, <b>why are they so afraid of letting this go to a vote?</b>  The best way to kill it is to have it voted down.  It would then never come up again.</p>
	<p>There was no way to divide a district in statute before.  Now there is a methodical process that we are engaged in which gets the issue out in the open.  If there are hidden agendas, they are coming from those who don't want it to come for a vote.  <b>Ultimately, if placed on the ballot, the voters decide.</b>  They have a right to form their own district if they desire!  <b>The schools belong to the people!</b>  The union didn't buy them.  Our parents and we did!</p>
	<p>Are there risks with forming a new district?  Of course, <b>you can't have freedom without risk.</b>  Could taxes go up?  (I think they will, even if we don't divide.)  Could we mess it all up?  Of course, but I have more faith in us than that.  We are a free people.  We built a state and a nation.  We can build a new district for our children's sake.</p>
|David N. Cox||divisionHotTopics|2~
Facts on School Size in Utah for 1999||   <center>
   <Table width=90% border=1 align=center cellpadding=10 cellspacing=1>
      <caption>The following information is based on data taken from the Fall Enrollment Report of Utah Public and Private Schools October 1, 1999</caption>
    <TR>
     <TD ALIGN="left">
      <ul>
       <li>85% of Utah's high school students are in schools that research says are too large. 82% for Jr. high and 72% for elementary.<br>
       <li>257 elementary schools, 82 jr. highs, and 56 high schools have more students than they should have.<br>
       <li>174,272 elementary students of 240,698 total elementary or 72% are in schools that are deemed by researchers to be too large.<br>
       <li>85,689 jr. high school students of 104,553 total or 82% are in schools that are too large.<br>
       <li>44 jr. highs over 1,000 for 52,821 students (50% are in a jr.high over1000)<br>
       <li>90,356 of 106,838 students (85%) are in 56 high schools with enrollments over levels researchers say are beneficial to student achievement. <br>
       <li>Only 6% of our students are in schools that are within the range researchers recommend.<br>
       <li>20,439 students are enrolled in 9 high schools that have over 2000 students each.<br>
       <li>31,743 or 30% of high school students are in schools as big or bigger than Columbine High School (~1800).<br>
      </ul>
      <p>Please read the other articles linked from this site which will give insight to these numbers and how they relate to appropriate school and district size.
     </td>
    </tr>
   </Table>
   </center>
|||facts|1~
Title|pdf|html|author|link|oldfile|section~